/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Editor: typeof import('./src/components/editor.vue')['default']
    EditSec: typeof import('./src/components/editSec.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Feedquery: typeof import('./src/components/feedquery.vue')['default']
    Gc: typeof import('./src/components/gc.vue')['default']
    Imgdetail: typeof import('./src/components/imgdetail.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    SelectPick: typeof import('./src/components/selectPick.vue')['default']
    Tabbar: typeof import('./src/components/tabbar.vue')['default']
    Tabs: typeof import('./src/components/tabs.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
    UserWork: typeof import('./src/components/userWork.vue')['default']
    VipPageContent: typeof import('./src/components/vipPageContent.vue')['default']
    Waterfall: typeof import('./src/components/waterfall.vue')['default']
  }
}
